define(['services/taskServices', 'services/staticData'], function (taskServices, staticData) {

   var eoList = ko.observableArray();
   var selectedEoItem = {};


   taskServices.eoQuickSearch("O").then(function (result) {
      if (!result.errorMessage) {

      }
      result =
      [
         {
            "dn": {
               "eo": 81,
               "eoStatus": "EOSA",
               "eventstatus": null,
               "createUser": 10000,
               "createDate": "2014-11-28 00:00:00",
               "createTime": "1970-01-01 15:06:45",
               "lastChangeUser": null,
               "lastChangeDate": null,
               "lastChangeTime": null,
               "deleFlag": "N",
               "customerOrder1": "",
               "customerOrder2": null,
               "customerOrder3": null,
               "memo": null,
               "reqDelDate1": "2014-11-28 00:00:00",
               "reqDelDate2": "2014-11-29 00:00:00",
               "reqDelDate3": null,
               "reqDelDate4": null,
               "reqDelTime1": null,
               "reqDelTime2": null,
               "reqDelTime3": null,
               "reqDelTime4": null,
               "businessPartner1": null,
               "businessPartner2": null,
               "businessPartner3": null,
               "eotype": "ER01",
               "eotrtype": "TTP4",
               "eotag": "0",
               "eotrvendor1": "HTCLD0002",
               "eotrvendor2": null,
               "eotrvendor3": null,
               "vendorOrder1": "",
               "vendorOrder2": null,
               "vendorOrder3": null,
               "deliverBP1": "",
               "deliverBP2": null,
               "deliverBP3": null,
               "depDate1": null,
               "depDate2": null,
               "depDate3": null,
               "arrDate1": null,
               "arrDate2": null,
               "arrDate3": null,
               "depTime1": null,
               "depTime2": null,
               "depTime3": null,
               "arrtime1": null,
               "arrtime2": null,
               "arrtime3": null,
               "depDate1act": null,
               "depDate2act": null,
               "depDate3act": null,
               "arrDate1act": null,
               "arrDate2act": null,
               "arrDate3act": null,
               "depTime1act": null,
               "depTime2act": null,
               "depTime3act": null,
               "arrtime1act": null,
               "arrtime2act": null,
               "arrtime3act": null,
               "scheduleVendor1": null,
               "scheduleVendor2": null,
               "scheduleVendor3": null,
               "scheduleClass1": null,
               "scheduleClass2": null,
               "scheduleClass3": null,
               "scheduleClassName1": null,
               "scheduleClassName2": null,
               "scheduleClassName3": null
            },
            "erHead": {
               "erID": 3,
               "erStatus": "ASGN",
               "project": "KRCC",
               "plannedID": "24",
               "omsOrder": null,
               "createUser": 10000,
               "createDate": "2014-11-28 00:00:00",
               "createTime": "1970-01-01 08:58:28",
               "lastChangeUser": null,
               "lastChangeDate": null,
               "lastChangeTime": null,
               "erType": "ER01",
               "erTRType": "TTP4",
               "erTag": "ETG2",
               "preERID": null,
               "preEOID": null,
               "customerOrder1": "A00227111111",
               "customerOrder2": "B0000134525",
               "customerOrder3": "C001111162",
               "preCustomerOrder1": null,
               "preCustomerOrder2": null,
               "preCustomerOrder3": null,
               "totalAmt": null,
               "totalWgt": null,
               "totalVol": null,
               "totalVolWgt": null,
               "resType1": null,
               "resType2": null,
               "resType3": null,
               "memo": null,
               "attachment": null,
               "reqDelDate": "2014-10-10 00:00:00",
               "reqDelTimeE": null,
               "reqDelTimeL": null,
               "recERDate": "2014-01-01 00:00:00",
               "recERTime": "1970-01-01 08:00:00",
               "pickERDate": "2014-01-01 00:00:00",
               "pickERStartTime": "1970-01-01 08:00:00",
               "pickERFinishTime": "1970-01-01 08:30:00",
               "oprERDate": "2014-01-01 00:00:00",
               "oprERStartUnloadTime": "1970-01-01 08:30:00",
               "oprERFinishUnloadTime": "1970-01-01 09:00:00",
               "oprERStartTime": "1970-01-01 09:00:00",
               "oprERFinishTime": "1970-01-01 10:00:00",
               "depAreaCode": "LOC0001",
               "depCustomer": "631099616",
               "depCustomerContact": "邵剑秋",
               "depCustomerEmail": "t@qac.com",
               "depCustomerPhone": "12345678",
               "depLocCode": "LOC0001",
               "depMemo": "测试附加信息",
               "recCustomer": "JQPT",
               "recCustomerContact": "th",
               "recCustomerEmail": "th@nc.cn",
               "recCustomerPhone": "87654321",
               "recLocCode": "124",
               "recMemo": "13/12312313/12323123/1231312",
               "deleFlag": "N",
               "depCountry": null,
               "depState": null,
               "depCity": null,
               "depDisc": null,
               "depGroup1": null,
               "depGroup2": null,
               "recCountry": null,
               "recState": null,
               "recCity": null,
               "recDisc": null,
               "recGroup1": null,
               "recGroup2": null,
               "contractID": null,
               "contractDate": null,
               "businessPartner1": null,
               "businessPartner2": null,
               "businessPartner3": null,
               "vendorOrder1": null,
               "vendorOrder2": null,
               "vendorOrder3": null,
               "mesUnit1": null,
               "mesUnit2": null,
               "mesUnit3": null,
               "resAmt1": null,
               "resAmt2": null,
               "resAmt3": null,
               "ertrvendor": null,
               "ertrtypeSM": null,
               "ertrvendorSM": null,
               "loadERStartTime": "1970-01-01 07:30:00",
               "loadERFinishTime": "1970-01-01 07:30:00"
            },
            "erItem": {
               "pk": {
                  "erID": 3,
                  "erITN": 2
               },
               "erITNStatus": "ASGN",
               "createDate": "2014-11-28 00:00:00",
               "createTime": "1970-01-01 08:58:28",
               "lastChangeUser": 10000,
               "lastChangeDate": "2014-11-28 00:00:00",
               "lastChangeTime": "1970-01-01 15:04:14",
               "erITNType": "ER01",
               "erITNTag": "ETG2",
               "status": "PKS1",
               "matIID": "13258165",
               "customerMatID": null,
               "customerOrder2": "B0000134525",
               "vendorOrder": null,
               "customer": null,
               "vendor": null,
               "amt": 17136,
               "wgt": 2,
               "vol": 2,
               "volWgt": 4,
               "longe": 1,
               "width": 1,
               "height": 2,
               "packNum": "DDD11",
               "packNum2": null,
               "packNum3": null,
               "memo": null,
               "deleFlag": "N",
               "routeID": null,
               "routeClassName": null,
               "routeClassID": "A4",
               "routeClassTimeS": null,
               "routeClassTimeE": null,
               "routePlanTag": null,
               "tranResType": null,
               "tranResID": null,
               "tranResLicense": null,
               "transDriverID": "133",
               "transResPlanTag": null,
               "trVendor": null,
               "itemSplitPlan": null,
               "project": null,
               "plannedID": null,
               "resType1": null,
               "resID1": "B1140J",
               "resType2": null,
               "resID2": null,
               "resType3": null,
               "resID3": null,
               "resMemo": null,
               "storageLocation": null,
               "dockLoaction": null,
               "portLocation": null,
               "grossWeight": null,
               "subPackNumner": null,
               "subPackNumner2": null,
               "subPackNumner3": null,
               "res1Vol": null,
               "res1NetWgt": null,
               "res1GrossWgt": null,
               "res2Vol": null,
               "res2NetWgt": null,
               "res2GrossWgt": null,
               "res3Vol": null,
               "res3NetWgt": null,
               "res3GrossWgt": null,
               "eoid": 81,
               "resAmt1": "17",
               "resAmtCS1": "M",
               "resAmt2": null,
               "resAmtCS2": null,
               "resAmt3": null,
               "resAmtCS3": null
            },
            "depCustomerDesc": "MOBIS",
            "recCustomerDesc": "上海金桥动力总成",
            "customerDesc": null,
            "vendorDesc": null,
            "scheduleVendor1Desc": null,
            "scheduleVendor2Desc": null,
            "scheduleVendor3Desc": null,
            "erstatusDesc": "ER行项目-已分配",
            "ertypeDesc": "HT-海通KRCC订单",
            "ertrtypeDesc": "陆运-循环取货",
            "eritntypeDesc": "HINGE ASM-L/GATE (BODY SI)",
            "matIIDDesc": null,
            "eostatusDesc": "EO-司机接单确认",
            "eotypeDesc": "HT-海通KRCC订单",
            "eotrtypeDesc": "陆运-循环取货",
            "eotagDesc": null,
            "eobp1Desc": null,
            "eobp2Desc": null,
            "eobp3Desc": null,
            "erbp1Desc": null,
            "erbp2Desc": null,
            "erbp3Desc": null,
            "trVendorDesc": null,
            "ertrtypeSMDesc": null,
            "ertrvendorDesc": null,
            "ertrvendorSMDesc": null,
            "eritnstatusDesc": "ER行项目-已分配",
            "eotrvendor1Desc": "天空物流",
            "eotrvendor2Desc": null,
            "eotrvendor3Desc": null,
            "deliverBP1Desc": null,
            "deliverBP2Desc": null,
            "deliverBP3Desc": null
         },
         {
            "dn": {
               "eo": 81,
               "eoStatus": "EOSA",
               "eventstatus": null,
               "createUser": 10000,
               "createDate": "2014-11-28 00:00:00",
               "createTime": "1970-01-01 15:06:45",
               "lastChangeUser": null,
               "lastChangeDate": null,
               "lastChangeTime": null,
               "deleFlag": "N",
               "customerOrder1": "",
               "customerOrder2": null,
               "customerOrder3": null,
               "memo": null,
               "reqDelDate1": "2014-11-28 00:00:00",
               "reqDelDate2": "2014-11-29 00:00:00",
               "reqDelDate3": null,
               "reqDelDate4": null,
               "reqDelTime1": null,
               "reqDelTime2": null,
               "reqDelTime3": null,
               "reqDelTime4": null,
               "businessPartner1": null,
               "businessPartner2": null,
               "businessPartner3": null,
               "eotype": "ER01",
               "eotrtype": "TTP4",
               "eotag": "0",
               "eotrvendor1": "HTCLD0002",
               "eotrvendor2": null,
               "eotrvendor3": null,
               "vendorOrder1": "",
               "vendorOrder2": null,
               "vendorOrder3": null,
               "deliverBP1": "",
               "deliverBP2": null,
               "deliverBP3": null,
               "depDate1": null,
               "depDate2": null,
               "depDate3": null,
               "arrDate1": null,
               "arrDate2": null,
               "arrDate3": null,
               "depTime1": null,
               "depTime2": null,
               "depTime3": null,
               "arrtime1": null,
               "arrtime2": null,
               "arrtime3": null,
               "depDate1act": null,
               "depDate2act": null,
               "depDate3act": null,
               "arrDate1act": null,
               "arrDate2act": null,
               "arrDate3act": null,
               "depTime1act": null,
               "depTime2act": null,
               "depTime3act": null,
               "arrtime1act": null,
               "arrtime2act": null,
               "arrtime3act": null,
               "scheduleVendor1": null,
               "scheduleVendor2": null,
               "scheduleVendor3": null,
               "scheduleClass1": null,
               "scheduleClass2": null,
               "scheduleClass3": null,
               "scheduleClassName1": null,
               "scheduleClassName2": null,
               "scheduleClassName3": null
            },
            "erHead": {
               "erID": 2,
               "erStatus": "ASGN",
               "project": "KRCC",
               "plannedID": "24",
               "omsOrder": null,
               "createUser": 10000,
               "createDate": "2014-11-28 00:00:00",
               "createTime": "1970-01-01 08:58:28",
               "lastChangeUser": null,
               "lastChangeDate": null,
               "lastChangeTime": null,
               "erType": "ER01",
               "erTRType": "TTP4",
               "erTag": "ETG2",
               "preERID": null,
               "preEOID": null,
               "customerOrder1": "A00227111111",
               "customerOrder2": "B0000134525",
               "customerOrder3": "C001111162",
               "preCustomerOrder1": null,
               "preCustomerOrder2": null,
               "preCustomerOrder3": null,
               "totalAmt": null,
               "totalWgt": null,
               "totalVol": null,
               "totalVolWgt": null,
               "resType1": null,
               "resType2": null,
               "resType3": null,
               "memo": null,
               "attachment": null,
               "reqDelDate": "2014-10-10 00:00:00",
               "reqDelTimeE": null,
               "reqDelTimeL": null,
               "recERDate": "2014-01-01 00:00:00",
               "recERTime": "1970-01-01 08:00:00",
               "pickERDate": "2014-01-01 00:00:00",
               "pickERStartTime": "1970-01-01 08:00:00",
               "pickERFinishTime": "1970-01-01 08:30:00",
               "oprERDate": "2014-01-01 00:00:00",
               "oprERStartUnloadTime": "1970-01-01 08:30:00",
               "oprERFinishUnloadTime": "1970-01-01 09:00:00",
               "oprERStartTime": "1970-01-01 09:00:00",
               "oprERFinishTime": "1970-01-01 10:00:00",
               "depAreaCode": "LOC0001",
               "depCustomer": "631099616",
               "depCustomerContact": "邵剑秋",
               "depCustomerEmail": "t@qac.com",
               "depCustomerPhone": "12345678",
               "depLocCode": "LOC0001",
               "depMemo": "测试附加信息",
               "recCustomer": "JQPT",
               "recCustomerContact": "th",
               "recCustomerEmail": "th@nc.cn",
               "recCustomerPhone": "87654321",
               "recLocCode": "124",
               "recMemo": "13/12312313/12323123/1231312",
               "deleFlag": "N",
               "depCountry": null,
               "depState": null,
               "depCity": null,
               "depDisc": null,
               "depGroup1": null,
               "depGroup2": null,
               "recCountry": null,
               "recState": null,
               "recCity": null,
               "recDisc": null,
               "recGroup1": null,
               "recGroup2": null,
               "contractID": null,
               "contractDate": null,
               "businessPartner1": null,
               "businessPartner2": null,
               "businessPartner3": null,
               "vendorOrder1": null,
               "vendorOrder2": null,
               "vendorOrder3": null,
               "mesUnit1": null,
               "mesUnit2": null,
               "mesUnit3": null,
               "resAmt1": null,
               "resAmt2": null,
               "resAmt3": null,
               "ertrvendor": null,
               "ertrtypeSM": null,
               "ertrvendorSM": null,
               "loadERStartTime": "1970-01-01 07:30:00",
               "loadERFinishTime": "1970-01-01 07:30:00"
            },
            "erItem": {
               "pk": {
                  "erID": 2,
                  "erITN": 2
               },
               "erITNStatus": "ASGN",
               "createDate": "2014-11-28 00:00:00",
               "createTime": "1970-01-01 08:58:28",
               "lastChangeUser": 10000,
               "lastChangeDate": "2014-11-28 00:00:00",
               "lastChangeTime": "1970-01-01 15:04:14",
               "erITNType": "ER01",
               "erITNTag": "ETG2",
               "status": "PKS1",
               "matIID": "13258165",
               "customerMatID": null,
               "customerOrder2": "B0000134525",
               "vendorOrder": null,
               "customer": null,
               "vendor": null,
               "amt": 17136,
               "wgt": 2,
               "vol": 2,
               "volWgt": 4,
               "longe": 1,
               "width": 1,
               "height": 2,
               "packNum": "DDD11",
               "packNum2": null,
               "packNum3": null,
               "memo": null,
               "deleFlag": "N",
               "routeID": null,
               "routeClassName": null,
               "routeClassID": "A3",
               "routeClassTimeS": null,
               "routeClassTimeE": null,
               "routePlanTag": null,
               "tranResType": null,
               "tranResID": null,
               "tranResLicense": null,
               "transDriverID": "133",
               "transResPlanTag": null,
               "trVendor": null,
               "itemSplitPlan": null,
               "project": null,
               "plannedID": null,
               "resType1": null,
               "resID1": "B1140J",
               "resType2": null,
               "resID2": null,
               "resType3": null,
               "resID3": null,
               "resMemo": null,
               "storageLocation": null,
               "dockLoaction": null,
               "portLocation": null,
               "grossWeight": null,
               "subPackNumner": null,
               "subPackNumner2": null,
               "subPackNumner3": null,
               "res1Vol": null,
               "res1NetWgt": null,
               "res1GrossWgt": null,
               "res2Vol": null,
               "res2NetWgt": null,
               "res2GrossWgt": null,
               "res3Vol": null,
               "res3NetWgt": null,
               "res3GrossWgt": null,
               "eoid": 81,
               "resAmt1": "17",
               "resAmtCS1": "M",
               "resAmt2": null,
               "resAmtCS2": null,
               "resAmt3": null,
               "resAmtCS3": null
            },
            "depCustomerDesc": "MOBIS",
            "recCustomerDesc": "上海金桥动力总成",
            "customerDesc": null,
            "vendorDesc": null,
            "scheduleVendor1Desc": null,
            "scheduleVendor2Desc": null,
            "scheduleVendor3Desc": null,
            "erstatusDesc": "ER行项目-已分配",
            "ertypeDesc": "HT-海通KRCC订单",
            "ertrtypeDesc": "陆运-循环取货",
            "eritntypeDesc": "HINGE ASM-L/GATE (BODY SI)",
            "matIIDDesc": null,
            "eostatusDesc": "EO-司机接单确认",
            "eotypeDesc": "HT-海通KRCC订单",
            "eotrtypeDesc": "陆运-循环取货",
            "eotagDesc": null,
            "eobp1Desc": null,
            "eobp2Desc": null,
            "eobp3Desc": null,
            "erbp1Desc": null,
            "erbp2Desc": null,
            "erbp3Desc": null,
            "trVendorDesc": null,
            "ertrtypeSMDesc": null,
            "ertrvendorDesc": null,
            "ertrvendorSMDesc": null,
            "eritnstatusDesc": "ER行项目-已分配",
            "eotrvendor1Desc": "天空物流",
            "eotrvendor2Desc": null,
            "eotrvendor3Desc": null,
            "deliverBP1Desc": null,
            "deliverBP2Desc": null,
            "deliverBP3Desc": null
         },
         {
            "dn": {
               "eo": 81,
               "eoStatus": "EOSA",
               "eventstatus": null,
               "createUser": 10000,
               "createDate": "2014-11-28 00:00:00",
               "createTime": "1970-01-01 15:06:45",
               "lastChangeUser": null,
               "lastChangeDate": null,
               "lastChangeTime": null,
               "deleFlag": "N",
               "customerOrder1": "",
               "customerOrder2": null,
               "customerOrder3": null,
               "memo": null,
               "reqDelDate1": "2014-11-28 00:00:00",
               "reqDelDate2": "2014-11-29 00:00:00",
               "reqDelDate3": null,
               "reqDelDate4": null,
               "reqDelTime1": null,
               "reqDelTime2": null,
               "reqDelTime3": null,
               "reqDelTime4": null,
               "businessPartner1": null,
               "businessPartner2": null,
               "businessPartner3": null,
               "eotype": "ER01",
               "eotrtype": "TTP4",
               "eotag": "0",
               "eotrvendor1": "HTCLD0002",
               "eotrvendor2": null,
               "eotrvendor3": null,
               "vendorOrder1": "",
               "vendorOrder2": null,
               "vendorOrder3": null,
               "deliverBP1": "",
               "deliverBP2": null,
               "deliverBP3": null,
               "depDate1": null,
               "depDate2": null,
               "depDate3": null,
               "arrDate1": null,
               "arrDate2": null,
               "arrDate3": null,
               "depTime1": null,
               "depTime2": null,
               "depTime3": null,
               "arrtime1": null,
               "arrtime2": null,
               "arrtime3": null,
               "depDate1act": null,
               "depDate2act": null,
               "depDate3act": null,
               "arrDate1act": null,
               "arrDate2act": null,
               "arrDate3act": null,
               "depTime1act": null,
               "depTime2act": null,
               "depTime3act": null,
               "arrtime1act": null,
               "arrtime2act": null,
               "arrtime3act": null,
               "scheduleVendor1": null,
               "scheduleVendor2": null,
               "scheduleVendor3": null,
               "scheduleClass1": null,
               "scheduleClass2": null,
               "scheduleClass3": null,
               "scheduleClassName1": null,
               "scheduleClassName2": null,
               "scheduleClassName3": null
            },
            "erHead": {
               "erID": 2,
               "erStatus": "ASGN",
               "project": "KRCC",
               "plannedID": "24",
               "omsOrder": null,
               "createUser": 10000,
               "createDate": "2014-11-28 00:00:00",
               "createTime": "1970-01-01 08:58:28",
               "lastChangeUser": null,
               "lastChangeDate": null,
               "lastChangeTime": null,
               "erType": "ER01",
               "erTRType": "TTP4",
               "erTag": "ETG2",
               "preERID": null,
               "preEOID": null,
               "customerOrder1": "A00227111111",
               "customerOrder2": "B0000134525",
               "customerOrder3": "C001111162",
               "preCustomerOrder1": null,
               "preCustomerOrder2": null,
               "preCustomerOrder3": null,
               "totalAmt": null,
               "totalWgt": null,
               "totalVol": null,
               "totalVolWgt": null,
               "resType1": null,
               "resType2": null,
               "resType3": null,
               "memo": null,
               "attachment": null,
               "reqDelDate": "2014-10-10 00:00:00",
               "reqDelTimeE": null,
               "reqDelTimeL": null,
               "recERDate": "2014-01-01 00:00:00",
               "recERTime": "1970-01-01 08:00:00",
               "pickERDate": "2014-01-01 00:00:00",
               "pickERStartTime": "1970-01-01 08:00:00",
               "pickERFinishTime": "1970-01-01 08:30:00",
               "oprERDate": "2014-01-01 00:00:00",
               "oprERStartUnloadTime": "1970-01-01 08:30:00",
               "oprERFinishUnloadTime": "1970-01-01 09:00:00",
               "oprERStartTime": "1970-01-01 09:00:00",
               "oprERFinishTime": "1970-01-01 10:00:00",
               "depAreaCode": "LOC0001",
               "depCustomer": "631099616",
               "depCustomerContact": "邵剑秋",
               "depCustomerEmail": "t@qac.com",
               "depCustomerPhone": "12345678",
               "depLocCode": "LOC0001",
               "depMemo": "测试附加信息",
               "recCustomer": "JQPT",
               "recCustomerContact": "th",
               "recCustomerEmail": "th@nc.cn",
               "recCustomerPhone": "87654321",
               "recLocCode": "124",
               "recMemo": "13/12312313/12323123/1231312",
               "deleFlag": "N",
               "depCountry": null,
               "depState": null,
               "depCity": null,
               "depDisc": null,
               "depGroup1": null,
               "depGroup2": null,
               "recCountry": null,
               "recState": null,
               "recCity": null,
               "recDisc": null,
               "recGroup1": null,
               "recGroup2": null,
               "contractID": null,
               "contractDate": null,
               "businessPartner1": null,
               "businessPartner2": null,
               "businessPartner3": null,
               "vendorOrder1": null,
               "vendorOrder2": null,
               "vendorOrder3": null,
               "mesUnit1": null,
               "mesUnit2": null,
               "mesUnit3": null,
               "resAmt1": null,
               "resAmt2": null,
               "resAmt3": null,
               "ertrvendor": null,
               "ertrtypeSM": null,
               "ertrvendorSM": null,
               "loadERStartTime": "1970-01-01 07:30:00",
               "loadERFinishTime": "1970-01-01 07:30:00"
            },
            "erItem": {
               "pk": {
                  "erID": 2,
                  "erITN": 2
               },
               "erITNStatus": "ASGN",
               "createDate": "2014-11-28 00:00:00",
               "createTime": "1970-01-01 08:58:28",
               "lastChangeUser": 10000,
               "lastChangeDate": "2014-11-28 00:00:00",
               "lastChangeTime": "1970-01-01 15:04:14",
               "erITNType": "ER01",
               "erITNTag": "ETG2",
               "status": "PKS1",
               "matIID": "13258165",
               "customerMatID": null,
               "customerOrder2": "B0000134525",
               "vendorOrder": null,
               "customer": null,
               "vendor": null,
               "amt": 17136,
               "wgt": 2,
               "vol": 2,
               "volWgt": 4,
               "longe": 1,
               "width": 1,
               "height": 2,
               "packNum": "DDD11",
               "packNum2": null,
               "packNum3": null,
               "memo": null,
               "deleFlag": "N",
               "routeID": null,
               "routeClassName": null,
               "routeClassID": "A3",
               "routeClassTimeS": null,
               "routeClassTimeE": null,
               "routePlanTag": null,
               "tranResType": null,
               "tranResID": null,
               "tranResLicense": null,
               "transDriverID": "133",
               "transResPlanTag": null,
               "trVendor": null,
               "itemSplitPlan": null,
               "project": null,
               "plannedID": null,
               "resType1": null,
               "resID1": "B1140J",
               "resType2": null,
               "resID2": null,
               "resType3": null,
               "resID3": null,
               "resMemo": null,
               "storageLocation": null,
               "dockLoaction": null,
               "portLocation": null,
               "grossWeight": null,
               "subPackNumner": null,
               "subPackNumner2": null,
               "subPackNumner3": null,
               "res1Vol": null,
               "res1NetWgt": null,
               "res1GrossWgt": null,
               "res2Vol": null,
               "res2NetWgt": null,
               "res2GrossWgt": null,
               "res3Vol": null,
               "res3NetWgt": null,
               "res3GrossWgt": null,
               "eoid": 81,
               "resAmt1": "17",
               "resAmtCS1": "M",
               "resAmt2": null,
               "resAmtCS2": null,
               "resAmt3": null,
               "resAmtCS3": null
            },
            "depCustomerDesc": "MOBIS",
            "recCustomerDesc": "上海金桥动力总成",
            "customerDesc": null,
            "vendorDesc": null,
            "scheduleVendor1Desc": null,
            "scheduleVendor2Desc": null,
            "scheduleVendor3Desc": null,
            "erstatusDesc": "ER行项目-已分配",
            "ertypeDesc": "HT-海通KRCC订单",
            "ertrtypeDesc": "陆运-循环取货",
            "eritntypeDesc": "HINGE ASM-L/GATE (BODY SI)",
            "matIIDDesc": null,
            "eostatusDesc": "EO-司机接单确认",
            "eotypeDesc": "HT-海通KRCC订单",
            "eotrtypeDesc": "陆运-循环取货",
            "eotagDesc": null,
            "eobp1Desc": null,
            "eobp2Desc": null,
            "eobp3Desc": null,
            "erbp1Desc": null,
            "erbp2Desc": null,
            "erbp3Desc": null,
            "trVendorDesc": null,
            "ertrtypeSMDesc": null,
            "ertrvendorDesc": null,
            "ertrvendorSMDesc": null,
            "eritnstatusDesc": "ER行项目-已分配",
            "eotrvendor1Desc": "天空物流",
            "eotrvendor2Desc": null,
            "eotrvendor3Desc": null,
            "deliverBP1Desc": null,
            "deliverBP2Desc": null,
            "deliverBP3Desc": null
         },
         {
            "dn": {
               "eo": 81,
               "eoStatus": "EOSA",
               "eventstatus": null,
               "createUser": 10000,
               "createDate": "2014-11-28 00:00:00",
               "createTime": "1970-01-01 15:06:45",
               "lastChangeUser": null,
               "lastChangeDate": null,
               "lastChangeTime": null,
               "deleFlag": "N",
               "customerOrder1": "",
               "customerOrder2": null,
               "customerOrder3": null,
               "memo": null,
               "reqDelDate1": "2014-11-28 00:00:00",
               "reqDelDate2": "2014-11-29 00:00:00",
               "reqDelDate3": null,
               "reqDelDate4": null,
               "reqDelTime1": null,
               "reqDelTime2": null,
               "reqDelTime3": null,
               "reqDelTime4": null,
               "businessPartner1": null,
               "businessPartner2": null,
               "businessPartner3": null,
               "eotype": "ER01",
               "eotrtype": "TTP4",
               "eotag": "0",
               "eotrvendor1": "HTCLD0002",
               "eotrvendor2": null,
               "eotrvendor3": null,
               "vendorOrder1": "",
               "vendorOrder2": null,
               "vendorOrder3": null,
               "deliverBP1": "",
               "deliverBP2": null,
               "deliverBP3": null,
               "depDate1": null,
               "depDate2": null,
               "depDate3": null,
               "arrDate1": null,
               "arrDate2": null,
               "arrDate3": null,
               "depTime1": null,
               "depTime2": null,
               "depTime3": null,
               "arrtime1": null,
               "arrtime2": null,
               "arrtime3": null,
               "depDate1act": null,
               "depDate2act": null,
               "depDate3act": null,
               "arrDate1act": null,
               "arrDate2act": null,
               "arrDate3act": null,
               "depTime1act": null,
               "depTime2act": null,
               "depTime3act": null,
               "arrtime1act": null,
               "arrtime2act": null,
               "arrtime3act": null,
               "scheduleVendor1": null,
               "scheduleVendor2": null,
               "scheduleVendor3": null,
               "scheduleClass1": null,
               "scheduleClass2": null,
               "scheduleClass3": null,
               "scheduleClassName1": null,
               "scheduleClassName2": null,
               "scheduleClassName3": null
            },
            "erHead": {
               "erID": 1,
               "erStatus": "ASGN",
               "project": "KRCC",
               "plannedID": "24",
               "omsOrder": null,
               "createUser": 10000,
               "createDate": "2014-11-28 00:00:00",
               "createTime": "1970-01-01 08:58:28",
               "lastChangeUser": null,
               "lastChangeDate": null,
               "lastChangeTime": null,
               "erType": "ER01",
               "erTRType": "TTP4",
               "erTag": "ETG2",
               "preERID": null,
               "preEOID": null,
               "customerOrder1": "A00227111111",
               "customerOrder2": "B0000134525",
               "customerOrder3": "C001111162",
               "preCustomerOrder1": null,
               "preCustomerOrder2": null,
               "preCustomerOrder3": null,
               "totalAmt": null,
               "totalWgt": null,
               "totalVol": null,
               "totalVolWgt": null,
               "resType1": null,
               "resType2": null,
               "resType3": null,
               "memo": null,
               "attachment": null,
               "reqDelDate": "2014-10-10 00:00:00",
               "reqDelTimeE": null,
               "reqDelTimeL": null,
               "recERDate": "2014-01-01 00:00:00",
               "recERTime": "1970-01-01 08:00:00",
               "pickERDate": "2014-01-01 00:00:00",
               "pickERStartTime": "1970-01-01 08:00:00",
               "pickERFinishTime": "1970-01-01 08:30:00",
               "oprERDate": "2014-01-01 00:00:00",
               "oprERStartUnloadTime": "1970-01-01 08:30:00",
               "oprERFinishUnloadTime": "1970-01-01 09:00:00",
               "oprERStartTime": "1970-01-01 09:00:00",
               "oprERFinishTime": "1970-01-01 10:00:00",
               "depAreaCode": "LOC0001",
               "depCustomer": "631099616",
               "depCustomerContact": "邵剑秋",
               "depCustomerEmail": "t@qac.com",
               "depCustomerPhone": "12345678",
               "depLocCode": "LOC0001",
               "depMemo": "测试附加信息",
               "recCustomer": "JQPT",
               "recCustomerContact": "th",
               "recCustomerEmail": "th@nc.cn",
               "recCustomerPhone": "87654321",
               "recLocCode": "124",
               "recMemo": "13/12312313/12323123/1231312",
               "deleFlag": "N",
               "depCountry": null,
               "depState": null,
               "depCity": null,
               "depDisc": null,
               "depGroup1": null,
               "depGroup2": null,
               "recCountry": null,
               "recState": null,
               "recCity": null,
               "recDisc": null,
               "recGroup1": null,
               "recGroup2": null,
               "contractID": null,
               "contractDate": null,
               "businessPartner1": null,
               "businessPartner2": null,
               "businessPartner3": null,
               "vendorOrder1": null,
               "vendorOrder2": null,
               "vendorOrder3": null,
               "mesUnit1": null,
               "mesUnit2": null,
               "mesUnit3": null,
               "resAmt1": null,
               "resAmt2": null,
               "resAmt3": null,
               "ertrvendor": null,
               "ertrtypeSM": null,
               "ertrvendorSM": null,
               "loadERStartTime": "1970-01-01 07:30:00",
               "loadERFinishTime": "1970-01-01 07:30:00"
            },
            "erItem": {
               "pk": {
                  "erID": 1,
                  "erITN": 2
               },
               "erITNStatus": "ASGN",
               "createDate": "2014-11-28 00:00:00",
               "createTime": "1970-01-01 08:58:28",
               "lastChangeUser": 10000,
               "lastChangeDate": "2014-11-28 00:00:00",
               "lastChangeTime": "1970-01-01 15:04:14",
               "erITNType": "ER01",
               "erITNTag": "ETG2",
               "status": "PKS1",
               "matIID": "13258165",
               "customerMatID": null,
               "customerOrder2": "B0000134525",
               "vendorOrder": null,
               "customer": null,
               "vendor": null,
               "amt": 17136,
               "wgt": 2,
               "vol": 2,
               "volWgt": 4,
               "longe": 1,
               "width": 1,
               "height": 2,
               "packNum": "DDD11",
               "packNum2": null,
               "packNum3": null,
               "memo": null,
               "deleFlag": "N",
               "routeID": null,
               "routeClassName": null,
               "routeClassID": "A2",
               "routeClassTimeS": null,
               "routeClassTimeE": null,
               "routePlanTag": null,
               "tranResType": null,
               "tranResID": null,
               "tranResLicense": null,
               "transDriverID": "133",
               "transResPlanTag": null,
               "trVendor": null,
               "itemSplitPlan": null,
               "project": null,
               "plannedID": null,
               "resType1": null,
               "resID1": "B1140J",
               "resType2": null,
               "resID2": null,
               "resType3": null,
               "resID3": null,
               "resMemo": null,
               "storageLocation": null,
               "dockLoaction": null,
               "portLocation": null,
               "grossWeight": null,
               "subPackNumner": null,
               "subPackNumner2": null,
               "subPackNumner3": null,
               "res1Vol": null,
               "res1NetWgt": null,
               "res1GrossWgt": null,
               "res2Vol": null,
               "res2NetWgt": null,
               "res2GrossWgt": null,
               "res3Vol": null,
               "res3NetWgt": null,
               "res3GrossWgt": null,
               "eoid": 81,
               "resAmt1": "17",
               "resAmtCS1": "M",
               "resAmt2": null,
               "resAmtCS2": null,
               "resAmt3": null,
               "resAmtCS3": null
            },
            "depCustomerDesc": "MOBIS",
            "recCustomerDesc": "上海金桥动力总成",
            "customerDesc": null,
            "vendorDesc": null,
            "scheduleVendor1Desc": null,
            "scheduleVendor2Desc": null,
            "scheduleVendor3Desc": null,
            "erstatusDesc": "ER行项目-已分配",
            "ertypeDesc": "HT-海通KRCC订单",
            "ertrtypeDesc": "陆运-循环取货",
            "eritntypeDesc": "HINGE ASM-L/GATE (BODY SI)",
            "matIIDDesc": null,
            "eostatusDesc": "EO-司机接单确认",
            "eotypeDesc": "HT-海通KRCC订单",
            "eotrtypeDesc": "陆运-循环取货",
            "eotagDesc": null,
            "eobp1Desc": null,
            "eobp2Desc": null,
            "eobp3Desc": null,
            "erbp1Desc": null,
            "erbp2Desc": null,
            "erbp3Desc": null,
            "trVendorDesc": null,
            "ertrtypeSMDesc": null,
            "ertrvendorDesc": null,
            "ertrvendorSMDesc": null,
            "eritnstatusDesc": "ER行项目-已分配",
            "eotrvendor1Desc": "天空物流",
            "eotrvendor2Desc": null,
            "eotrvendor3Desc": null,
            "deliverBP1Desc": null,
            "deliverBP2Desc": null,
            "deliverBP3Desc": null
         }
      ];


      var arr = taskServices.organizeResult(result);
      arr.forEach(
         function (item) {
            eoList.push(item);
         }
      );


   });

   var onItemClick = function (item) {

   };

   var execute = function () {

   };

   //public methods & Properties
   return {
      selectedEoItem: selectedEoItem,
      onItemClick: onItemClick,
      eoList: eoList,
      execute: execute
   };
});
